baseurl: ""
permalink: /:title/
url: "https://codonaft.com"
title: codonaft
description: Conscious Free and Open Source Software Crafting

#collections:
#  posts:
#    output: true
#    permalink: /:title
#    lang: en

defaults:
  - scope:
      path: 'legacy/*'
    values: {}
  - scope:
      path: ''
    values:
      lang: en
      str:
        share: Please share, follow and all this!
        fix_typo: Fix typo
        support_other_ways: Support me in other ways
        share_or_support_other_ways: Like what I do?<br>Your support keeps me going!
        read_more: Read more &rightarrow;
        share_on: Share on
        add_to: Add to
        email: Email
        tweet: Tweet
        pin_it: Pin it
        next_post: Next post
        previous_post: Previous post
        next_page: Next
        previous_page: Prev
        javascript_required_comments: Please enable JavaScript to view comments.
        p2p_player_warning: Too slow? Try
        onion_mirror: onion mirror
        i2p_mirror: i2p mirror
        or: or
        leave_comment_on_upstream: Leave comment using
  - scope:
      path: 'ru/*'
    values:
      permalink: /ru/:title/
      lang: ru
      str:
        description: Осознанная разработка свободного ПО
        share: Поделись находкой с друзьями!
        fix_typo: Исправить опечатку
        support_other_ways: Поддержать меня другими способами
        share_or_support_other_ways: Нравится то, что я делаю?<br>Буду рад твоей поддержке!
        read_more: Читать дальше &rightarrow;
        share_on: Поделиться на
        add_to: Add to
        email: Email
        tweet: Твитнуть
        pin_it: Pin it
        next_post: Следующий пост
        previous_post: Предыдущий пост
        next_page: Дальше
        previous_page: Назад
        javascript_required_comments: Please enable JavaScript to view comments.
        p2p_player_warning: Медленно грузится? Попробуй
        onion_mirror: зеркало
        i2p_mirror: другое зеркало
        or: или
        leave_comment_on_upstream: Оставить коммент через

theme_settings:
  site_repo_url: https://github.com/codonaft/codonaft.github.io
  site_repo_branch: master

  avatar: assets/img/avatar.webp
  gravatar:

  header_text_feature_image: assets/img/pexels/motherboard.jpg

  date_format: "%Y-%m-%d"

  email_address:
  behance:
  bitbucket:
  dribbble:
  facebook: codonaft
  flickr:
  gitlab:
  github: codonaft
  i2p: http://codonftbnpdkjwyflssto3iklawhuthbe37l6swigegqkyyfmiqa.b32.i2p
  instagram:
  telegram_ru: codonaft_official
  keybase:
  linkedin: AlexanderLopatin
  patreon: alopatindev
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tor: http://codonaftbvv4j5k7nsrdivbdblycqrng5ls2qkng6lm77svepqjyxgid.onion
  tumblr:
  twitter:
  vimeo:
  vk: codonaft
  wordpress:
  youtube: "@codonaftFOSS"
  youtube_ru: "@codonaft"

  btc: "1MpA1jqkTJTPcFNwrWghQZ7nRWS5gjBKNe"
  eth: "0xe7c5549246a7eb2a8398b947c2175e5b34bb3fcc"
  ltc: "LSBjTftxfzRPDMb3QaX8NMGTH3w1CyjDbz"
  zec: "t1bPyVoWijTjzSZqDeh1aFfSERRKhBNjp9S"
  lightning: "alopatindev@rizful.com"

  share_buttons:
    vk:
    telegram: true
    facebook:
    twitter: true
    viber:
    whatsapp:
    email:
    tumblr:
    pinterest:
    pocket:
    reddit:
    linkedin: true
    wordpress:

  google_analytics:
  disqus_shortname:
  typed: false
  katex: false
  zapthreads: true

  nostr:
    enabled: true
    npub: npub1alptdev5srcw2hxg03567p4k6xs3lgj7f6545suc0rzp0xw98svse7rg94
    nprofile: nprofile1qqswls4kuk2gpu89tny8c6d0q6mdrggl5f0ya226gwv833qhn8zncxgprpmhxue69uhkummnw3ezucm0v3hkuctxwshxxmmdqyt8wumn8ghj7un9d3shjtnwdaehgu3wvfskueqpz3mhxue69uhhyetvv9ujuerpd46hxtnfdu9dfmdy
    community: codonaft
    max_comment_length: 5000
    min_read_pow: 7

    spam_api: https://spam.nostr.band/spam_api
    profile_relays:
    - wss://user.kindpag.es
    - wss://hist.nostr.land
    - wss://relay.vertexlab.io
    relays:
    - wss://nos.lol
    - wss://relay.damus.io
    - wss://wotr.relatr.xyz
    - wss://nostr.data.haus
    read_cache_relays:
    - wss://relay.primal.net
    - wss://nostr.codonaft.com
    - wss://archive.orly.dev

    spam_api_overwrite: ''
    profile_relays_overwrite: []
    relays_overwrite: []
    read_cache_relays_overwrite: []

  special_page:
    search:
      icon: search # Assuming page link and icon are the same
      enabled: false
    tags:
      icon: tags
      enabled: false

  #external_google_fonts: "Noto Color Emoji:400|Open Sans:400|Open Sans:700|Roboto:100|Roboto:300|Roboto Condensed:400"

  post_navigation: true

  p2p_player:
    swarm_prefix: https://media.codonaft.com
    media_urls:
    - https://media.codonaft.com
    - https://media-cached.codonaft.com
    media_urls_overwrite: []
    trackers:
    - wss://media.codonaft.com/announce
    - wss://tracker.webtorrent.dev
    #- wss://tracker.openwebtorrent.com
    ice_servers:
    - stun:stun.framasoft.org
    - stun:stun.l.google.com:19302
    #- stun:stun.tula.nu
    #- stun:stun.nextcloud.com
    #- stun:stun.imp.ch
    #- stun:stunserver2024.stunprotocol.org
    #- stun:stun.hot-chilli.net
    #- stun:stun.axialys.net
    #- stun:stun.vomessen.de
    #- stun:stun.streamnow.ch
    #- stun:stun.antisip.com
    #- stun:stun.cloudflare.com:3478
    storyboard:
      max_size: 16383
      interval_sec: 8
      tile_width: 400

exclude:
  - .backup
  - .build

excerpt_separator: <!--more-->
markdown: kramdown
timezone: UTC
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins: [jekyll-seo-tag]
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  blanklines: true
  ignore:
    envs: []
exclude: [vendor]
include: [.well-known]
