bind = "127.0.0.1:28019"
api = true

[ui]
favicon_url = "data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMzIgMzIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iMTYiIGN5PSIxNiIgcj0iMTEiLz48L3N2Zz4="
show_autocomplete = false
show_settings_link = false

[image_search]
enabled = true
max_download_size = 4194304

[engines]
bing = false
minecraft_wiki = false

[urls.replace]
"medium.com" = "scribe.rip"
".medium.com" = "scribe.rip"
"x.com" = "xcancel.com"
".x.com" = "xcancel.com"

[urls.weight]
".zhihu.com" = 0
